apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-drc1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-drc1
    app.kubernetes.io/part-of: ci10t-776-0002-app
  name: devfile-sample-drc1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-drc1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-drc1
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0002-tenant/ci10t-776-0002-app/devfile-sample-drc1@sha256:b3d59a32895b2f53e2b6cb5737d3a565415d2f02252d93f3ac337537b1bfa4d8
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
